### PR TITLE
Fix various windows keyboard ailments

### LINKED ISSUE #171: Panel refresh doesn't work when clicking on Windows 11
Ctrl+R works when the panel is maximized though. This is on the latest build as of today. I may have some time coming up to look at this.

### LINKED ISSUE #172: Ctrl+Shift+A (reset all) does not work on Windows 11
There is no way that I'm aware to refresh / reset all panels. This is on the latest build as of today.

### PR DESCRIPTION
**Pull request by martypenner**
Commit log by fix/feature:

- fix(windows): allow global refresh command to work
- fix(windows): ensure refresh button in maximized panes works
- feat: add a util for getting the current platform
- feat: add a constant for Cmd or Ctrl based on the current platform
- feat: use cmd or ctrl appropriately in various UI text

I snuck in the last three commits, but am happy to make changes if that's reaching too far.

Fixes #171, fixes #172.

### CODE REVIEW

**Comment by swyxio** [comment]
awesome thanks for this! will just check that it runs locally on macs

**Comment by swyxio** [comment]
image

this code shows the wrong key on my mac, prob because the returned process.platform string is not what you expected

**Comment by martypenner** [comment]
Darn. Will take a look within the next couple of days. I can spin this up on multiple machines to verify.

**Comment by martypenner** [comment]
Oh, I see you already fixed! Thanks for catching that. I had a hard time finding any docs on electron's platform variable.

**Pull request merged**
